version: '3.4'

services:
  backend-service-task-executor:
    ports:
      - "${MY_BACKEND_SERVICE_TASK_EXECUTOR_WEB_PORT_HTTP}:${MY_BACKEND_SERVICE_TASK_EXECUTOR_WEB_PORT_HTTP}"

  external-mongo:
    ports:
      - "${MY_EXTERNAL_MONGO_PORT}:${MY_EXTERNAL_MONGO_PORT}"

  external-mongo-express:
    ports:
      - "${MY_EXTERNAL_MONGO_EXPRESS_PORT}:8081"

  external-rabbitmq:
    ports:
      - "${MY_EXTERNAL_RABBITMQ_MANAGENENT_PORT}:${MY_EXTERNAL_RABBITMQ_MANAGENENT_PORT}"
      - "${MY_EXTERNAL_RABBITMQ_PORT}:${MY_EXTERNAL_RABBITMQ_PORT}"
