services:
  backend-gateway-web-app:
    container_name: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_IMAGE_NAME}
    environment:
      - App__Authentication__Audience=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_AUTHENTICATION_AUDIENCE}
      - App__Authentication__Issuer=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_AUTHENTICATION_ISSUER}
      - App__Authentication__Key=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_AUTHENTICATION_KEY}
      - App__Writer__ApiAddress=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_WRITER_API_ADDRESS}
    networks:
      - network-backend
    depends_on:
      backend-writer-web-app:
        condition: service_started

  backend-writer-web-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_WEB_APP_IMAGE_NAME}
    environment:
      - App__Authentication__Audience=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_AUTHENTICATION_AUDIENCE}
      - App__Authentication__Issuer=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_AUTHENTICATION_ISSUER}
      - App__Authentication__Key=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_AUTHENTICATION_KEY}
      - App__IsRetryEnabledByOrchestrator=false
      - App__Language=ru
      - App__PostgreSQL__ConnectionStringName=PostgreSQL
      - App__PostgreSQL__Database=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_DATABASE}
      - App__PostgreSQL__Password=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_PASSWORD}
      - App__PostgreSQL__Port=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_PORT}
      - App__PostgreSQL__Server=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_SERVER}
      - App__PostgreSQL__UserId=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_USERID}
    networks:
      - network-backend

networks:
  network-backend:
    attachable: true
