services:
  external-pgadmin:
    volumes:
      - ${MY_SERVICE_EXTERNAL_PGADMIN_HOST_FOLDER}:${MY_SERVICE_EXTERNAL_PGADMIN_CONTAINER_FOLDER}
    ports:
      - "${MY_SERVICE_EXTERNAL_PGADMIN_HOST_PORT}:${MY_SERVICE_EXTERNAL_PGADMIN_CONTAINER_PORT}"

  external-postgres:
    volumes:
      - ${MY_SERVICE_EXTERNAL_POSTGRES_HOST_FOLDER_DATA}:${MY_SERVICE_EXTERNAL_POSTGRES_CONTAINER_FOLDER_DATA}
    ports:
      - "${MY_SERVICE_EXTERNAL_POSTGRES_HOST_PORT}:${MY_SERVICE_EXTERNAL_POSTGRES_CONTAINER_PORT}"
