services:
  backend-gateway-web-app:
    container_name: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_IMAGE_NAME}
    environment:
      - App__Authentication__Audience=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_AUTHENTICATION_AUDIENCE}
      - App__Authentication__Issuer=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_AUTHENTICATION_ISSUER}
      - App__Authentication__Key=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_AUTHENTICATION_KEY}
      - App__Writer__ApiAddress=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_WRITER_API_ADDRESS}
    networks:
      - network-backend

networks:
  network-backend:
    attachable: true
