version: '3.4'

services:
  backend-task-manager-web:
    ports:
      - "${MY_BACKEND_TASK_MANAGER_WEB_PORT_HTTP}:${MY_BACKEND_TASK_MANAGER_WEB_PORT_HTTP}"

  backend-gateway-web:
    ports:
      - "${MY_BACKEND_GATEWAY_WEB_PORT_HTTP}:${MY_BACKEND_GATEWAY_WEB_PORT_HTTP}"
      - "${MY_BACKEND_GATEWAY_WEB_PORT_HTTPS}:${MY_BACKEND_GATEWAY_WEB_PORT_HTTPS}"

  backend-task-executor-web:
    ports:
      - "${MY_BACKEND_TASK_EXECUTOR_WEB_PORT_HTTP}:${MY_BACKEND_TASK_EXECUTOR_WEB_PORT_HTTP}"

  backend-task-reader-web:
    ports:
      - "${MY_BACKEND_TASK_READER_WEB_PORT_HTTP}:${MY_BACKEND_TASK_READER_WEB_PORT_HTTP}"

  backend-task-storage-web:
    ports:
      - "${MY_BACKEND_TASK_STORAGE_WEB_PORT_HTTP}:${MY_BACKEND_TASK_STORAGE_WEB_PORT_HTTP}"

  external-mongo:
    ports:
      - "${MY_EXTERNAL_MONGO_PORT}:${MY_EXTERNAL_MONGO_PORT}"

  external-mongo-express:
    ports:
      - "${MY_EXTERNAL_MONGO_EXPRESS_PORT}:8081"

  external-nginx:
    ports:
      - "${MY_EXTERNAL_NGINX_PORT_HTTP}:${MY_EXTERNAL_NGINX_PORT_HTTP}"
      - "${MY_EXTERNAL_NGINX_PORT_HTTPS}:${MY_EXTERNAL_NGINX_PORT_HTTPS}"

  external-postgres:
    ports:
      - "${MY_EXTERNAL_POSTGRES_PORT}:${MY_EXTERNAL_POSTGRES_PORT}"

  external-pgadmin:
    ports:
      - "${MY_EXTERNAL_PGADMIN_PORT}:80"

  external-pgbouncer:
    ports:
      - "${MY_EXTERNAL_PGBOUNCER_PORT}:${MY_EXTERNAL_PGBOUNCER_PORT}"

  external-rabbitmq:
    ports:
      - "${MY_EXTERNAL_RABBITMQ_MANAGENENT_PORT}:${MY_EXTERNAL_RABBITMQ_MANAGENENT_PORT}"
      - "${MY_EXTERNAL_RABBITMQ_PORT}:${MY_EXTERNAL_RABBITMQ_PORT}"

  frontend-web-reactvite:
    build:
      context: .
      dockerfile: ${MY_FRONTEND_WEB_REACTVITE_PATH}debug/Dockerfile
    environment:
      - WATCHPACK_POLLING=true #https://stackoverflow.com/questions/72023425/my-react-18-app-does-not-reload-automatically-i-try-to-click-on-the-create-new-p
    volumes:
      - ./${MY_FRONTEND_WEB_REACTVITE_PATH}:/app
      - ./${MY_FRONTEND_WEB_REACTVITE_PATH}debug/node_modules:/app/node_modules
    ports:
      - "${MY_FRONTEND_WEB_REACTVITE_PORT_HTTP}:${MY_FRONTEND_WEB_REACTVITE_PORT_HTTP}"

  frontend-web-reactvite-debug:
    container_name: ${MY_CONTAINER_NAME_PEFIX}frontend-web-reactvite-debug
    image: ${MY_IMAGE_PEFIX}frontend-web-reactvite-debug
    build:
      context: .
      dockerfile: ${MY_FRONTEND_WEB_REACTVITE_PATH}Dockerfile
      args:
        - APP_PATH=${MY_FRONTEND_WEB_REACTVITE_PATH}
    ports:
      - "${MY_FRONTEND_WEB_REACTVITE_PORT_HTTP_DEBUG}:80"
    networks:
      - network-frontend
